version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/yamldefault

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install dependencies
          command: |
            make build
      
      - save_cache:
          paths:
              - /go/pkg/
          key: v1-pkg-cache

      - run:
          name: Run tests
          command: |
            make test
      
      - store_test_results:
            path: /unit

workflows:
  version: 2
  test:
    jobs:
      - test
